# ML-05 — Feature Vector and Leakage/Privacy Check

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/MA-1305/Project_Mahin-1305/blob/main/work/notebooks/w03_feature_leakage_check.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Build the feature vector

*Code that actually builds it — engineered features, categorical handling, fills.*

In [17]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import os
import pandas as pd

print(os.getcwd())
print(os.listdir("/content"))

/content/Project_Mahin-1305/work/notebooks
['.config', 'Project_Mahin-1305', 'sample_data']

In [18]:
import pandas as pd

df = pd.read_csv("../../data/raw/content_refresh_anonymized.csv")

print("Shape:", df.shape)
display(df.head())

Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 2. Feature notes (meaning, missing, categorical, available-when?)

*For each feature: what it means, how missing values are handled, and whether it exists BEFORE the moment you predict.*

In [19]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
print(df.columns.tolist())

['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

In [20]:
display(df.dtypes)

content_id                 object
client_id                  object
search_volume             float64
competition               float64
competition_level          object
cpc                       float64
content_type               object
main_intent                object
word_count                float64
char_count                float64
provider_used              object
model_used                 object
impressions_90d             int64
clicks_90d                  int64
pageviews_90d               int64
sessions_90d                int64
users_90d                   int64
engaged_sessions_90d        int64
ai_sessions_90d             int64
scroll_events_90d           int64
days_with_impressions       int64
days_with_sessions          int64
impressions_last_30d        int64
clicks_last_30d             int64
sessions_last_30d           int64
impressions_prev_30d        int64
clicks_prev_30d             int64
sessions_prev_30d           int64
content_age_days            int64
age_tier                   object
age_tier_order              int64
days_since_last_update      int64
freshness_tier             object
word_count_tier            object
char_count_tier            object
ctr                       float64
avg_position              float64
engagement_rate           float64
scroll_rate               float64
ai_traffic_pct            float64
impression_tier            object
position_tier              object
trend_direction            object
trend_pct                 float64
dtype: object

## 3. The leakage hunt

*Attack your own features: label-derived columns, future windows, product flags. Show the test.*

In [21]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
print("Columns that may contain leakage:")
for col in df.columns:
    name = col.lower()
    if any(word in name for word in ["target", "label", "future", "next", "outcome", "conversion", "rank", "position"]):
        print("-", col)

Columns that may contain leakage:
- avg_position
- position_tier

In [22]:
print("All columns:")
for i, col in enumerate(df.columns):
    print(i, col)

All columns:
0 content_id
1 client_id
2 search_volume
3 competition
4 competition_level
5 cpc
6 content_type
7 main_intent
8 word_count
9 char_count
10 provider_used
11 model_used
12 impressions_90d
13 clicks_90d
14 pageviews_90d
15 sessions_90d
16 users_90d
17 engaged_sessions_90d
18 ai_sessions_90d
19 scroll_events_90d
20 days_with_impressions
21 days_with_sessions
22 impressions_last_30d
23 clicks_last_30d
24 sessions_last_30d
25 impressions_prev_30d
26 clicks_prev_30d
27 sessions_prev_30d
28 content_age_days
29 age_tier
30 age_tier_order
31 days_since_last_update
32 freshness_tier
33 word_count_tier
34 char_count_tier
35 ctr
36 avg_position
37 engagement_rate
38 scroll_rate
39 ai_traffic_pct
40 impression_tier
41 position_tier
42 trend_direction
43 trend_pct

## 4. What I excluded and why

*The list of fields you refused to use — with one line of why each.*

In [23]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
for i, col in enumerate(df.columns):
    print(i, col, "->", df[col].dtype)

0 content_id -> object
1 client_id -> object
2 search_volume -> float64
3 competition -> float64
4 competition_level -> object
5 cpc -> float64
6 content_type -> object
7 main_intent -> object
8 word_count -> float64
9 char_count -> float64
10 provider_used -> object
11 model_used -> object
12 impressions_90d -> int64
13 clicks_90d -> int64
14 pageviews_90d -> int64
15 sessions_90d -> int64
16 users_90d -> int64
17 engaged_sessions_90d -> int64
18 ai_sessions_90d -> int64
19 scroll_events_90d -> int64
20 days_with_impressions -> int64
21 days_with_sessions -> int64
22 impressions_last_30d -> int64
23 clicks_last_30d -> int64
24 sessions_last_30d -> int64
25 impressions_prev_30d -> int64
26 clicks_prev_30d -> int64
27 sessions_prev_30d -> int64
28 content_age_days -> int64
29 age_tier -> object
30 age_tier_order -> int64
31 days_since_last_update -> int64
32 freshness_tier -> object
33 word_count_tier -> object
34 char_count_tier -> object
35 ctr -> float64
36 avg_position -> float64
37 engagement_rate -> float64
38 scroll_rate -> float64
39 ai_traffic_pct -> float64
40 impression_tier -> object
41 position_tier -> object
42 trend_direction -> object
43 trend_pct -> float64

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.